LANGUAGE_MAP: dict[str, str] = {
    "韩语": "ko_KR",
    "英语": "en_US",
    "日语": "ja_JP",
    "泰语": "th_TH",
    "越南语": "vi_VN",
    "阿拉伯语": "ar_AE",
    "德语": "de_DE",
    "西班牙语": "es_ES",
    "法语": "fr_FR",
    "印地语": "hi_IN",
    "印度尼西亚语": "id_ID",
    "意大利语": "it_IT",
    "马来西亚语": "ms_MY",
    "葡萄牙语": "pt_PT",
    "土耳其语": "tr_TR",
    "简体中文": "zh_CN",
    "繁体中文": "zh_TW",
}

DEFAULT_MATERIAL_QUERY_PARAMS: dict = {
    "type": 1,
    "pageSize": 100,
    "deptOrUser": "",
    "createBy": "",
    "deptIds": [],
    "videoIds": [],
    "linkIds": [],
    "weatherNewShortPlay": None,
    "today": "",
    "materialAccount": "",
    "channelNoFilterType": 1,
    "channelNos": [],
}

FIXED_DELIVERY_TASK_PARAMS: dict = {
    "status": "ON",
    "validTimeList": [{"startTime": "00:00:00", "endTime": "23:59:59"}],
    "runInterval": 60,
    "stopConditionList": [
        {"conditionType": 2, "conditionValue": 10},
        {"conditionType": 3, "conditionValue": 10},
    ],
    "materialRule": {
        "materialRuleType": 2,
        "sortType": "2",
        "materialDeliveryTimeType": 3,
        "materialCreateOrDeliveryDays": 3,
        "materialCountType": 1,
        "materialRepeatType": 2,
        "materialRepeatNum": 1,
        "adSetNum": 1,
        "adMaterialNum": 30,
        "materialCostType": 1,
        "rangeType": 2,
        "rangeSymbol": 1,
    },
    "objective": "OUTCOME_SALES",
    "budgetStrategy": 1,
    "budgetType": 1,
    "buyingType": "AUCTION",
    "bidStrategy": "LOWEST_COST_WITHOUT_CAP",
    "spendCapType": 1,
    "applicationId": "",
    "objectStoreUrl": "http://play.google.com/store/apps/details?id=com.netshort.abroad",
    "optimizationGoal": "VALUE",
    "attributionSpec": "[{\"event_type\":\"CLICK_THROUGH\",\"window_days\":7}]",
    "attributionSpecValue": "1",
    "customEventType": "PURCHASE",
    "bidAmount": None,
    "billingEvent": "IMPRESSIONS",
    "enrollStatus": "OPT_IN",
    "callToActionTypes": "WATCH_MORE",
    "deeplinkUrl": "",
    "creativeFeaturesSpec": "[\"inline_comment\",\"image_templates\",\"image_touchups\",\"video_auto_crop\",\"image_brightness_and_contrast\",\"enhance_cta\",\"text_optimizations\",\"audios\"]",
    "channelPackageId": 6,
    "dailyBudget": "30.00",
    "appStore": "1",
}
